# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{proxy_stack}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman", "Lincoln Stoll"]
  s.date = %q{2009-11-22}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/proxy_stack.rb",
     "lib/proxy_stack/config.ru",
     "lib/proxy_stack/config/config.rb",
     "lib/proxy_stack/proxy_stack.rb",
     "lib/proxy_stack/tasks/proxy_stack.rake",
     "spec/proxy_stack_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hassox/proxy_stack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple Light weight proxy}
  s.test_files = [
    "spec/proxy_stack_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pancake>, [">= 0.1.24"])
    else
      s.add_dependency(%q<pancake>, [">= 0.1.24"])
    end
  else
    s.add_dependency(%q<pancake>, [">= 0.1.24"])
  end
end

